packageExtensions:
  '@vanilla-extract/webpack-plugin@^2.1.0':
    dependencies:
      '@vanilla-extract/css': ^1.6.0
  react-dev-utils@^10.2.1:
    dependencies:
      typescript: ^4.3.5
      webpack: ^5.9.0
  relay-compiler@^12.0.0:
    dependencies:
      relay-compiler-language-typescript: '^14.1.0'
      '@types/react-relay': '^11.0.2'
      '@types/relay-runtime': '^11.0.4'
      typescript: '3.7.7'
  babel-plugin-relay@^12.0.0:
    dependencies:
      '@babel/runtime': '^7.15.4'
  '@endemolshinegroup/cosmiconfig-typescript-loader@^3.0.2':
    dependencies:
      typescript: '~3.7.2'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.0.1.cjs
