packageExtensions:
  "@vanilla-extract/webpack-plugin@^1.1.0":
    dependencies:
      "@vanilla-extract/css": ^1.2.3
  react-dev-utils@^10.2.1:
    dependencies:
      typescript: ^4.3.5
      webpack: ^5.9.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
