yarnPath: .yarn/releases/yarn-3.0.0.cjs

packageExtensions:
  react-dev-utils@^10.2.1:
    dependencies:
      webpack: ^5.9.0
      typescript: '^4.3.5'
  '@vanilla-extract/webpack-plugin@^1.1.0':
    dependencies:
      '@vanilla-extract/css': ^1.2.3
