# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

on:
  push:
    branches:
      - main
  pull_request:

name: Build

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-all:
    name: Build all packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v4
        with:
          path: |
            .yarn/unplugged/
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1

      - name: Install the unplugged dependencies and check that the Yarn files do not change during the installation process. If an error occurs, run "yarn install" and commit and push.
        run: |
          yarn install --immutable
        shell: bash

      - uses: actions/cache/restore@v4
        with:
          path: |
            **/dist/
            **/build/
            **/.next/
            **/.ultra.cache.json
          key: ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-
            ${{ runner.os }}-ultra-v1-main-

      - name: Build the entire monorepo
        run: |
          yarn build

      - uses: actions/cache/save@v4
        if: github.event_name == 'push'
        with:
          path: |
            **/dist/
            **/build/
            **/.next/
            **/.ultra.cache.json
          key: ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
