name: Test for Pull request

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Yarn
        run: npm install yarn

      - name: Update Yarn Berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test